#!/usr/bin/env bash
echo "rRNA and tRNA counter"
echo "Author Soheil A. Neshat"
echo "Email soheilneshat@gmail.com"
echo "Please cite Neshat, S. A. (2022). Microbiome studies on anaerobic digestion using genome–resolved multi–omics."
echo "Please run this shell script inside the directory containing the outputs of barrnap (.gff) and tRNAScan-SE (.o)"
echo "Run chmod 777 RNA_count.sh if you get the error message permission denied. "
echo " "
echo " "

#Author Soheil A. Neshat
#Email soheilneshat@gmail.com
#Please cite Neshat, S. A. (2022). Microbiome studies on anaerobic digestion using genome–resolved multi–omics.

echo "Genome" "S5" "S16" "S23" "Partial"> rRNA_count.txt

for i in *.gff
do
S5=$(grep -c 5S_rRNA $i) 
S16=$(grep -c 16S_rRNA $i)
S23=$(grep -c 23S_rRNA $i)
P=$(grep -c partial $i)
echo $i ${S5} ${S16} ${S23} $P>> rRNA_count.txt
done

echo "Genome" "tRNA_count" "Pseudo" >> tRNA_count.txt
for i in *.o
do
n=$(sed '4q;d' $i | cut -d'_' -f1)
tRNA=$(grep -c $n $i)
PS=$(grep -c pseudo $i)
echo $i ${tRNA} ${PS} >> tRNA_count.txt
done
